// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqxnMCU1gKoU1Bk5IXaY1pXkJK9gq4kVE',
    appId: '1:641139638317:web:55d7e2a5e1247b663c38a4',
    messagingSenderId: '641139638317',
    projectId: 'food-fridge-50d20',
    authDomain: 'food-fridge-50d20.firebaseapp.com',
    storageBucket: 'food-fridge-50d20.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCesBvWBbgegU8_D7OT2gnhxyZCpuE1rPw',
    appId: '1:641139638317:android:b51be3bb04c6588a3c38a4',
    messagingSenderId: '641139638317',
    projectId: 'food-fridge-50d20',
    storageBucket: 'food-fridge-50d20.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxHfTc7aldEczl4bvmmLDXUHpLn2VtUKw',
    appId: '1:641139638317:ios:ddc4515a80a14f043c38a4',
    messagingSenderId: '641139638317',
    projectId: 'food-fridge-50d20',
    storageBucket: 'food-fridge-50d20.firebasestorage.app',
    androidClientId: '641139638317-lrnsghdb6acg3sahkvea9gcoe0qe4ove.apps.googleusercontent.com',
    iosClientId: '641139638317-jff7g1sjqajof71b2m9uhmi1alkfmokt.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodfridgeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxHfTc7aldEczl4bvmmLDXUHpLn2VtUKw',
    appId: '1:641139638317:ios:ddc4515a80a14f043c38a4',
    messagingSenderId: '641139638317',
    projectId: 'food-fridge-50d20',
    storageBucket: 'food-fridge-50d20.firebasestorage.app',
    androidClientId: '641139638317-lrnsghdb6acg3sahkvea9gcoe0qe4ove.apps.googleusercontent.com',
    iosClientId: '641139638317-jff7g1sjqajof71b2m9uhmi1alkfmokt.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodfridgeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqxnMCU1gKoU1Bk5IXaY1pXkJK9gq4kVE',
    appId: '1:641139638317:web:846fe77ff0589f263c38a4',
    messagingSenderId: '641139638317',
    projectId: 'food-fridge-50d20',
    authDomain: 'food-fridge-50d20.firebaseapp.com',
    storageBucket: 'food-fridge-50d20.firebasestorage.app',
  );

}